
version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@1.3.1
  eb: circleci/aws-elastic-beanstalk@1.0.0
  # aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1
jobs:

  build:

    docker:
      - image: "cimg/base:stable"

    # filters:
    #   branches:
    #     only:
    #       - main

    steps:
      - node/install:
          node-version: "16.13.2"
      - checkout
      - aws-cli/setup
      - eb/setup

      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
      - run:
          name: Back-End Install
          command: |
            npm run backend:install
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          name: Back-End Build
          command: |
            npm run backend:build
      - run:
          name: Deploy Front-End 
          command: |
            npm run frontend:deploy
      - run:
          name: Pointing to EB Environment
          command: |
            eb init --profile default
            eb use udagram-api2-dev --profile default
      - run: 
          name: Pass EB Environment Variables
          command: |
            eb setenv PORT=$PORT POSTGRES_HOST=$POSTGRES_HOST POSTGRES_PASSWORD=$POSTGRES_PASSWORD POSTGRES_USERNAME=$POSTGRES_USERNAME POSTGRES_DB=$POSTGRES_DB DB_PORT=$DB_PORT AWS_BUCKET=$AWS_BUCKET JWT_SECRET=$JWT_SECRET URL=$URL
      - run: 
          name: Backend Deploy
          command: |
            npm run backend:deploy


